<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>

              
            <script type="text/x-magento-init">
                 {
                    "*": {
                        "Magento_Ui/js/core/app": {
                            "components":{
                                "qty_change": {
                                    "component": "Prueba_Promo/js/view/product/view/qty_change",
                                    "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
                                }
                            }
                        }
                    }
                 }
            </script>
             

            <div class="control" data-bind="scope: 'qty_change'">
                <button data-bind="click: decreaseQty">-</button>
                <input data-bind="value: qty()"
                       type="number"
                       name="qty"
                       id="qty"
                       min="8 "
                       value="<?= $block->getProductDefaultOtu() * 1  ?>"
                       title="<?=  $block->escapeHtmlAtt(__('Qty'))?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <button data-bind="click: increaseQty">+</button>

            </div>
        </div>
        <div>
            <input type="text" name="remarks" id="remarks" maxlength="255" placeholder="Remarks" />                                                                 >
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if($block->isRedirectToCartEnabled()) :?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/validate-product": {
                "radioCheckboxClosest" : ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function($)){
        'use strict';
        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function(form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit:false
                });
                widget.catalogAddToCart('submitForm', $(form));
              return false;
            }
        })
    }
</script>
<?php endif; ?>


